/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PayCheckoutRouteImport } from './routes/pay.checkout'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedRoutineRouteImport } from './routes/_authenticated/routine'
import { Route as AuthenticatedResultsRouteImport } from './routes/_authenticated/results'
import { Route as AuthenticatedRegistrationsRouteImport } from './routes/_authenticated/registrations'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedPaymentsRouteImport } from './routes/_authenticated/payments'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as AuthenticatedNoticesRouteImport } from './routes/_authenticated/notices'
import { Route as AuthenticatedMyCoursesRouteImport } from './routes/_authenticated/my-courses'
import { Route as AuthenticatedLabProjectsRouteImport } from './routes/_authenticated/lab-projects'
import { Route as AuthenticatedFacultyRouteImport } from './routes/_authenticated/faculty'
import { Route as AuthenticatedCourseMaterialsRouteImport } from './routes/_authenticated/course-materials'
import { Route as AuthenticatedClassesRouteImport } from './routes/_authenticated/classes'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiRoutineIndexRouteImport } from './routes/api/routine/index'
import { Route as ApiRegistrationsIndexRouteImport } from './routes/api/registrations/index'
import { Route as ApiPaymentsIndexRouteImport } from './routes/api/payments/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiNoticesIndexRouteImport } from './routes/api/notices/index'
import { Route as ApiLabProjectsIndexRouteImport } from './routes/api/lab-projects/index'
import { Route as ApiGradesIndexRouteImport } from './routes/api/grades/index'
import { Route as ApiCoursesIndexRouteImport } from './routes/api/courses/index'
import { Route as ApiCourseMaterialsIndexRouteImport } from './routes/api/course-materials/index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as ApiStudentsIdRouteImport } from './routes/api/students/$id'
import { Route as ApiRegistrationsIdRouteImport } from './routes/api/registrations/$id'
import { Route as ApiNoticesIdRouteImport } from './routes/api/notices/$id'
import { Route as AuthenticatedFacultyBlockedRouteImport } from './routes/_authenticated/faculty.blocked'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSemestersRouteImport } from './routes/_authenticated/admin.semesters'
import { Route as AuthenticatedAdminGradesRouteImport } from './routes/_authenticated/admin.grades'
import { Route as AuthenticatedAdminGradeScaleRouteImport } from './routes/_authenticated/admin.grade-scale'
import { Route as AuthenticatedAdminAuditRouteImport } from './routes/_authenticated/admin.audit'
import { Route as ApiStudentsIdCoursesRouteImport } from './routes/api/students/$id.courses'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiGradesPublishOfferingIdRouteImport } from './routes/api/grades/publish.$offeringId'
import { Route as AuthenticatedFacultyBlockedStudentUserIdRouteImport } from './routes/_authenticated/faculty.blocked.$studentUserId'
import { Route as AuthenticatedAdminStudentsNewRouteImport } from './routes/_authenticated/admin.students.new'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PayCheckoutRoute = PayCheckoutRouteImport.update({
  id: '/pay/checkout',
  path: '/pay/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoutineRoute = AuthenticatedRoutineRouteImport.update({
  id: '/routine',
  path: '/routine',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedResultsRoute = AuthenticatedResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRegistrationsRoute =
  AuthenticatedRegistrationsRouteImport.update({
    id: '/registrations',
    path: '/registrations',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPaymentsRoute = AuthenticatedPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNoticesRoute = AuthenticatedNoticesRouteImport.update({
  id: '/notices',
  path: '/notices',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMyCoursesRoute = AuthenticatedMyCoursesRouteImport.update({
  id: '/my-courses',
  path: '/my-courses',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedLabProjectsRoute =
  AuthenticatedLabProjectsRouteImport.update({
    id: '/lab-projects',
    path: '/lab-projects',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedFacultyRoute = AuthenticatedFacultyRouteImport.update({
  id: '/faculty',
  path: '/faculty',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCourseMaterialsRoute =
  AuthenticatedCourseMaterialsRouteImport.update({
    id: '/course-materials',
    path: '/course-materials',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedClassesRoute = AuthenticatedClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoutineIndexRoute = ApiRoutineIndexRouteImport.update({
  id: '/api/routine/',
  path: '/api/routine/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsIndexRoute = ApiRegistrationsIndexRouteImport.update({
  id: '/api/registrations/',
  path: '/api/registrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIndexRoute = ApiPaymentsIndexRouteImport.update({
  id: '/api/payments/',
  path: '/api/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoticesIndexRoute = ApiNoticesIndexRouteImport.update({
  id: '/api/notices/',
  path: '/api/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabProjectsIndexRoute = ApiLabProjectsIndexRouteImport.update({
  id: '/api/lab-projects/',
  path: '/api/lab-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradesIndexRoute = ApiGradesIndexRouteImport.update({
  id: '/api/grades/',
  path: '/api/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesIndexRoute = ApiCoursesIndexRouteImport.update({
  id: '/api/courses/',
  path: '/api/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseMaterialsIndexRoute = ApiCourseMaterialsIndexRouteImport.update({
  id: '/api/course-materials/',
  path: '/api/course-materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStudentsIdRoute = ApiStudentsIdRouteImport.update({
  id: '/api/students/$id',
  path: '/api/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsIdRoute = ApiRegistrationsIdRouteImport.update({
  id: '/api/registrations/$id',
  path: '/api/registrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoticesIdRoute = ApiNoticesIdRouteImport.update({
  id: '/api/notices/$id',
  path: '/api/notices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFacultyBlockedRoute =
  AuthenticatedFacultyBlockedRouteImport.update({
    id: '/blocked',
    path: '/blocked',
    getParentRoute: () => AuthenticatedFacultyRoute,
  } as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSemestersRoute =
  AuthenticatedAdminSemestersRouteImport.update({
    id: '/semesters',
    path: '/semesters',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGradesRoute =
  AuthenticatedAdminGradesRouteImport.update({
    id: '/grades',
    path: '/grades',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminGradeScaleRoute =
  AuthenticatedAdminGradeScaleRouteImport.update({
    id: '/grade-scale',
    path: '/grade-scale',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAuditRoute = AuthenticatedAdminAuditRouteImport.update({
  id: '/audit',
  path: '/audit',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const ApiStudentsIdCoursesRoute = ApiStudentsIdCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ApiStudentsIdRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGradesPublishOfferingIdRoute =
  ApiGradesPublishOfferingIdRouteImport.update({
    id: '/api/grades/publish/$offeringId',
    path: '/api/grades/publish/$offeringId',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedFacultyBlockedStudentUserIdRoute =
  AuthenticatedFacultyBlockedStudentUserIdRouteImport.update({
    id: '/$studentUserId',
    path: '/$studentUserId',
    getParentRoute: () => AuthenticatedFacultyBlockedRoute,
  } as any)
const AuthenticatedAdminStudentsNewRoute =
  AuthenticatedAdminStudentsNewRouteImport.update({
    id: '/students/new',
    path: '/students/new',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/classes': typeof AuthenticatedClassesRoute
  '/course-materials': typeof AuthenticatedCourseMaterialsRoute
  '/faculty': typeof AuthenticatedFacultyRouteWithChildren
  '/lab-projects': typeof AuthenticatedLabProjectsRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registrations': typeof AuthenticatedRegistrationsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/api/health': typeof ApiHealthRoute
  '/pay/checkout': typeof PayCheckoutRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/grade-scale': typeof AuthenticatedAdminGradeScaleRoute
  '/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/admin/semesters': typeof AuthenticatedAdminSemestersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faculty/blocked': typeof AuthenticatedFacultyBlockedRouteWithChildren
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/grades/': typeof ApiGradesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/faculty/blocked/$studentUserId': typeof AuthenticatedFacultyBlockedStudentUserIdRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/classes': typeof AuthenticatedClassesRoute
  '/course-materials': typeof AuthenticatedCourseMaterialsRoute
  '/faculty': typeof AuthenticatedFacultyRouteWithChildren
  '/lab-projects': typeof AuthenticatedLabProjectsRoute
  '/my-courses': typeof AuthenticatedMyCoursesRoute
  '/notices': typeof AuthenticatedNoticesRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/payments': typeof AuthenticatedPaymentsRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/registrations': typeof AuthenticatedRegistrationsRoute
  '/results': typeof AuthenticatedResultsRoute
  '/routine': typeof AuthenticatedRoutineRoute
  '/api/health': typeof ApiHealthRoute
  '/pay/checkout': typeof PayCheckoutRoute
  '/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/admin/grade-scale': typeof AuthenticatedAdminGradeScaleRoute
  '/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/admin/semesters': typeof AuthenticatedAdminSemestersRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/faculty/blocked': typeof AuthenticatedFacultyBlockedRouteWithChildren
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/api/course-materials': typeof ApiCourseMaterialsIndexRoute
  '/api/courses': typeof ApiCoursesIndexRoute
  '/api/grades': typeof ApiGradesIndexRoute
  '/api/lab-projects': typeof ApiLabProjectsIndexRoute
  '/api/notices': typeof ApiNoticesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/payments': typeof ApiPaymentsIndexRoute
  '/api/registrations': typeof ApiRegistrationsIndexRoute
  '/api/routine': typeof ApiRoutineIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/faculty/blocked/$studentUserId': typeof AuthenticatedFacultyBlockedStudentUserIdRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/classes': typeof AuthenticatedClassesRoute
  '/_authenticated/course-materials': typeof AuthenticatedCourseMaterialsRoute
  '/_authenticated/faculty': typeof AuthenticatedFacultyRouteWithChildren
  '/_authenticated/lab-projects': typeof AuthenticatedLabProjectsRoute
  '/_authenticated/my-courses': typeof AuthenticatedMyCoursesRoute
  '/_authenticated/notices': typeof AuthenticatedNoticesRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/_authenticated/payments': typeof AuthenticatedPaymentsRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/registrations': typeof AuthenticatedRegistrationsRoute
  '/_authenticated/results': typeof AuthenticatedResultsRoute
  '/_authenticated/routine': typeof AuthenticatedRoutineRoute
  '/api/health': typeof ApiHealthRoute
  '/pay/checkout': typeof PayCheckoutRoute
  '/_authenticated/admin/audit': typeof AuthenticatedAdminAuditRoute
  '/_authenticated/admin/grade-scale': typeof AuthenticatedAdminGradeScaleRoute
  '/_authenticated/admin/grades': typeof AuthenticatedAdminGradesRoute
  '/_authenticated/admin/semesters': typeof AuthenticatedAdminSemestersRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/faculty/blocked': typeof AuthenticatedFacultyBlockedRouteWithChildren
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/grades/': typeof ApiGradesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/_authenticated/admin/students/new': typeof AuthenticatedAdminStudentsNewRoute
  '/_authenticated/faculty/blocked/$studentUserId': typeof AuthenticatedFacultyBlockedStudentUserIdRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/admin'
    | '/classes'
    | '/course-materials'
    | '/faculty'
    | '/lab-projects'
    | '/my-courses'
    | '/notices'
    | '/overview'
    | '/payments'
    | '/profile'
    | '/registrations'
    | '/results'
    | '/routine'
    | '/api/health'
    | '/pay/checkout'
    | '/admin/audit'
    | '/admin/grade-scale'
    | '/admin/grades'
    | '/admin/semesters'
    | '/admin/users'
    | '/faculty/blocked'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/admin/'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/grades/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/registrations/'
    | '/api/routine/'
    | '/api/students/'
    | '/admin/students/new'
    | '/faculty/blocked/$studentUserId'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/classes'
    | '/course-materials'
    | '/faculty'
    | '/lab-projects'
    | '/my-courses'
    | '/notices'
    | '/overview'
    | '/payments'
    | '/profile'
    | '/registrations'
    | '/results'
    | '/routine'
    | '/api/health'
    | '/pay/checkout'
    | '/admin/audit'
    | '/admin/grade-scale'
    | '/admin/grades'
    | '/admin/semesters'
    | '/admin/users'
    | '/faculty/blocked'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/admin'
    | '/api/course-materials'
    | '/api/courses'
    | '/api/grades'
    | '/api/lab-projects'
    | '/api/notices'
    | '/api/notifications'
    | '/api/payments'
    | '/api/registrations'
    | '/api/routine'
    | '/api/students'
    | '/admin/students/new'
    | '/faculty/blocked/$studentUserId'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/admin'
    | '/_authenticated/classes'
    | '/_authenticated/course-materials'
    | '/_authenticated/faculty'
    | '/_authenticated/lab-projects'
    | '/_authenticated/my-courses'
    | '/_authenticated/notices'
    | '/_authenticated/overview'
    | '/_authenticated/payments'
    | '/_authenticated/profile'
    | '/_authenticated/registrations'
    | '/_authenticated/results'
    | '/_authenticated/routine'
    | '/api/health'
    | '/pay/checkout'
    | '/_authenticated/admin/audit'
    | '/_authenticated/admin/grade-scale'
    | '/_authenticated/admin/grades'
    | '/_authenticated/admin/semesters'
    | '/_authenticated/admin/users'
    | '/_authenticated/faculty/blocked'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/_authenticated/admin/'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/grades/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/registrations/'
    | '/api/routine/'
    | '/api/students/'
    | '/_authenticated/admin/students/new'
    | '/_authenticated/faculty/blocked/$studentUserId'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  PayCheckoutRoute: typeof PayCheckoutRoute
  ApiNoticesIdRoute: typeof ApiNoticesIdRoute
  ApiRegistrationsIdRoute: typeof ApiRegistrationsIdRoute
  ApiStudentsIdRoute: typeof ApiStudentsIdRouteWithChildren
  ApiCourseMaterialsIndexRoute: typeof ApiCourseMaterialsIndexRoute
  ApiCoursesIndexRoute: typeof ApiCoursesIndexRoute
  ApiGradesIndexRoute: typeof ApiGradesIndexRoute
  ApiLabProjectsIndexRoute: typeof ApiLabProjectsIndexRoute
  ApiNoticesIndexRoute: typeof ApiNoticesIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPaymentsIndexRoute: typeof ApiPaymentsIndexRoute
  ApiRegistrationsIndexRoute: typeof ApiRegistrationsIndexRoute
  ApiRoutineIndexRoute: typeof ApiRoutineIndexRoute
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
  ApiGradesPublishOfferingIdRoute: typeof ApiGradesPublishOfferingIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/checkout': {
      id: '/pay/checkout'
      path: '/pay/checkout'
      fullPath: '/pay/checkout'
      preLoaderRoute: typeof PayCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/routine': {
      id: '/_authenticated/routine'
      path: '/routine'
      fullPath: '/routine'
      preLoaderRoute: typeof AuthenticatedRoutineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/results': {
      id: '/_authenticated/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof AuthenticatedResultsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/registrations': {
      id: '/_authenticated/registrations'
      path: '/registrations'
      fullPath: '/registrations'
      preLoaderRoute: typeof AuthenticatedRegistrationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/payments': {
      id: '/_authenticated/payments'
      path: '/payments'
      fullPath: '/payments'
      preLoaderRoute: typeof AuthenticatedPaymentsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/notices': {
      id: '/_authenticated/notices'
      path: '/notices'
      fullPath: '/notices'
      preLoaderRoute: typeof AuthenticatedNoticesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/my-courses': {
      id: '/_authenticated/my-courses'
      path: '/my-courses'
      fullPath: '/my-courses'
      preLoaderRoute: typeof AuthenticatedMyCoursesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/lab-projects': {
      id: '/_authenticated/lab-projects'
      path: '/lab-projects'
      fullPath: '/lab-projects'
      preLoaderRoute: typeof AuthenticatedLabProjectsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/faculty': {
      id: '/_authenticated/faculty'
      path: '/faculty'
      fullPath: '/faculty'
      preLoaderRoute: typeof AuthenticatedFacultyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/course-materials': {
      id: '/_authenticated/course-materials'
      path: '/course-materials'
      fullPath: '/course-materials'
      preLoaderRoute: typeof AuthenticatedCourseMaterialsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/classes': {
      id: '/_authenticated/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof AuthenticatedClassesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/routine/': {
      id: '/api/routine/'
      path: '/api/routine'
      fullPath: '/api/routine/'
      preLoaderRoute: typeof ApiRoutineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/': {
      id: '/api/registrations/'
      path: '/api/registrations'
      fullPath: '/api/registrations/'
      preLoaderRoute: typeof ApiRegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/': {
      id: '/api/payments/'
      path: '/api/payments'
      fullPath: '/api/payments/'
      preLoaderRoute: typeof ApiPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notices/': {
      id: '/api/notices/'
      path: '/api/notices'
      fullPath: '/api/notices/'
      preLoaderRoute: typeof ApiNoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab-projects/': {
      id: '/api/lab-projects/'
      path: '/api/lab-projects'
      fullPath: '/api/lab-projects/'
      preLoaderRoute: typeof ApiLabProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grades/': {
      id: '/api/grades/'
      path: '/api/grades'
      fullPath: '/api/grades/'
      preLoaderRoute: typeof ApiGradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses/': {
      id: '/api/courses/'
      path: '/api/courses'
      fullPath: '/api/courses/'
      preLoaderRoute: typeof ApiCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-materials/': {
      id: '/api/course-materials/'
      path: '/api/course-materials'
      fullPath: '/api/course-materials/'
      preLoaderRoute: typeof ApiCourseMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/students/$id': {
      id: '/api/students/$id'
      path: '/api/students/$id'
      fullPath: '/api/students/$id'
      preLoaderRoute: typeof ApiStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/$id': {
      id: '/api/registrations/$id'
      path: '/api/registrations/$id'
      fullPath: '/api/registrations/$id'
      preLoaderRoute: typeof ApiRegistrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notices/$id': {
      id: '/api/notices/$id'
      path: '/api/notices/$id'
      fullPath: '/api/notices/$id'
      preLoaderRoute: typeof ApiNoticesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/faculty/blocked': {
      id: '/_authenticated/faculty/blocked'
      path: '/blocked'
      fullPath: '/faculty/blocked'
      preLoaderRoute: typeof AuthenticatedFacultyBlockedRouteImport
      parentRoute: typeof AuthenticatedFacultyRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/semesters': {
      id: '/_authenticated/admin/semesters'
      path: '/semesters'
      fullPath: '/admin/semesters'
      preLoaderRoute: typeof AuthenticatedAdminSemestersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/grades': {
      id: '/_authenticated/admin/grades'
      path: '/grades'
      fullPath: '/admin/grades'
      preLoaderRoute: typeof AuthenticatedAdminGradesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/grade-scale': {
      id: '/_authenticated/admin/grade-scale'
      path: '/grade-scale'
      fullPath: '/admin/grade-scale'
      preLoaderRoute: typeof AuthenticatedAdminGradeScaleRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/audit': {
      id: '/_authenticated/admin/audit'
      path: '/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AuthenticatedAdminAuditRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/api/students/$id/courses': {
      id: '/api/students/$id/courses'
      path: '/courses'
      fullPath: '/api/students/$id/courses'
      preLoaderRoute: typeof ApiStudentsIdCoursesRouteImport
      parentRoute: typeof ApiStudentsIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grades/publish/$offeringId': {
      id: '/api/grades/publish/$offeringId'
      path: '/api/grades/publish/$offeringId'
      fullPath: '/api/grades/publish/$offeringId'
      preLoaderRoute: typeof ApiGradesPublishOfferingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/faculty/blocked/$studentUserId': {
      id: '/_authenticated/faculty/blocked/$studentUserId'
      path: '/$studentUserId'
      fullPath: '/faculty/blocked/$studentUserId'
      preLoaderRoute: typeof AuthenticatedFacultyBlockedStudentUserIdRouteImport
      parentRoute: typeof AuthenticatedFacultyBlockedRoute
    }
    '/_authenticated/admin/students/new': {
      id: '/_authenticated/admin/students/new'
      path: '/students/new'
      fullPath: '/admin/students/new'
      preLoaderRoute: typeof AuthenticatedAdminStudentsNewRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAuditRoute: typeof AuthenticatedAdminAuditRoute
  AuthenticatedAdminGradeScaleRoute: typeof AuthenticatedAdminGradeScaleRoute
  AuthenticatedAdminGradesRoute: typeof AuthenticatedAdminGradesRoute
  AuthenticatedAdminSemestersRoute: typeof AuthenticatedAdminSemestersRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedAdminStudentsNewRoute: typeof AuthenticatedAdminStudentsNewRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAuditRoute: AuthenticatedAdminAuditRoute,
  AuthenticatedAdminGradeScaleRoute: AuthenticatedAdminGradeScaleRoute,
  AuthenticatedAdminGradesRoute: AuthenticatedAdminGradesRoute,
  AuthenticatedAdminSemestersRoute: AuthenticatedAdminSemestersRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedAdminStudentsNewRoute: AuthenticatedAdminStudentsNewRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedFacultyBlockedRouteChildren {
  AuthenticatedFacultyBlockedStudentUserIdRoute: typeof AuthenticatedFacultyBlockedStudentUserIdRoute
}

const AuthenticatedFacultyBlockedRouteChildren: AuthenticatedFacultyBlockedRouteChildren =
  {
    AuthenticatedFacultyBlockedStudentUserIdRoute:
      AuthenticatedFacultyBlockedStudentUserIdRoute,
  }

const AuthenticatedFacultyBlockedRouteWithChildren =
  AuthenticatedFacultyBlockedRoute._addFileChildren(
    AuthenticatedFacultyBlockedRouteChildren,
  )

interface AuthenticatedFacultyRouteChildren {
  AuthenticatedFacultyBlockedRoute: typeof AuthenticatedFacultyBlockedRouteWithChildren
}

const AuthenticatedFacultyRouteChildren: AuthenticatedFacultyRouteChildren = {
  AuthenticatedFacultyBlockedRoute:
    AuthenticatedFacultyBlockedRouteWithChildren,
}

const AuthenticatedFacultyRouteWithChildren =
  AuthenticatedFacultyRoute._addFileChildren(AuthenticatedFacultyRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedClassesRoute: typeof AuthenticatedClassesRoute
  AuthenticatedCourseMaterialsRoute: typeof AuthenticatedCourseMaterialsRoute
  AuthenticatedFacultyRoute: typeof AuthenticatedFacultyRouteWithChildren
  AuthenticatedLabProjectsRoute: typeof AuthenticatedLabProjectsRoute
  AuthenticatedMyCoursesRoute: typeof AuthenticatedMyCoursesRoute
  AuthenticatedNoticesRoute: typeof AuthenticatedNoticesRoute
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
  AuthenticatedPaymentsRoute: typeof AuthenticatedPaymentsRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedRegistrationsRoute: typeof AuthenticatedRegistrationsRoute
  AuthenticatedResultsRoute: typeof AuthenticatedResultsRoute
  AuthenticatedRoutineRoute: typeof AuthenticatedRoutineRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedClassesRoute: AuthenticatedClassesRoute,
  AuthenticatedCourseMaterialsRoute: AuthenticatedCourseMaterialsRoute,
  AuthenticatedFacultyRoute: AuthenticatedFacultyRouteWithChildren,
  AuthenticatedLabProjectsRoute: AuthenticatedLabProjectsRoute,
  AuthenticatedMyCoursesRoute: AuthenticatedMyCoursesRoute,
  AuthenticatedNoticesRoute: AuthenticatedNoticesRoute,
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
  AuthenticatedPaymentsRoute: AuthenticatedPaymentsRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedRegistrationsRoute: AuthenticatedRegistrationsRoute,
  AuthenticatedResultsRoute: AuthenticatedResultsRoute,
  AuthenticatedRoutineRoute: AuthenticatedRoutineRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiStudentsIdRouteChildren {
  ApiStudentsIdCoursesRoute: typeof ApiStudentsIdCoursesRoute
}

const ApiStudentsIdRouteChildren: ApiStudentsIdRouteChildren = {
  ApiStudentsIdCoursesRoute: ApiStudentsIdCoursesRoute,
}

const ApiStudentsIdRouteWithChildren = ApiStudentsIdRoute._addFileChildren(
  ApiStudentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  PayCheckoutRoute: PayCheckoutRoute,
  ApiNoticesIdRoute: ApiNoticesIdRoute,
  ApiRegistrationsIdRoute: ApiRegistrationsIdRoute,
  ApiStudentsIdRoute: ApiStudentsIdRouteWithChildren,
  ApiCourseMaterialsIndexRoute: ApiCourseMaterialsIndexRoute,
  ApiCoursesIndexRoute: ApiCoursesIndexRoute,
  ApiGradesIndexRoute: ApiGradesIndexRoute,
  ApiLabProjectsIndexRoute: ApiLabProjectsIndexRoute,
  ApiNoticesIndexRoute: ApiNoticesIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPaymentsIndexRoute: ApiPaymentsIndexRoute,
  ApiRegistrationsIndexRoute: ApiRegistrationsIndexRoute,
  ApiRoutineIndexRoute: ApiRoutineIndexRoute,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
  ApiGradesPublishOfferingIdRoute: ApiGradesPublishOfferingIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
