/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiRoutineIndexRouteImport } from './routes/api/routine/index'
import { Route as ApiResultsIndexRouteImport } from './routes/api/results/index'
import { Route as ApiPaymentsIndexRouteImport } from './routes/api/payments/index'
import { Route as ApiNoticesIndexRouteImport } from './routes/api/notices/index'
import { Route as ApiLabProjectsIndexRouteImport } from './routes/api/lab-projects/index'
import { Route as ApiCoursesIndexRouteImport } from './routes/api/courses/index'
import { Route as ApiCourseMaterialsIndexRouteImport } from './routes/api/course-materials/index'
import { Route as ApiStudentsIdCoursesRouteImport } from './routes/api/students/$id.courses'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoutineIndexRoute = ApiRoutineIndexRouteImport.update({
  id: '/api/routine/',
  path: '/api/routine/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResultsIndexRoute = ApiResultsIndexRouteImport.update({
  id: '/api/results/',
  path: '/api/results/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIndexRoute = ApiPaymentsIndexRouteImport.update({
  id: '/api/payments/',
  path: '/api/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoticesIndexRoute = ApiNoticesIndexRouteImport.update({
  id: '/api/notices/',
  path: '/api/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabProjectsIndexRoute = ApiLabProjectsIndexRouteImport.update({
  id: '/api/lab-projects/',
  path: '/api/lab-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesIndexRoute = ApiCoursesIndexRouteImport.update({
  id: '/api/courses/',
  path: '/api/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseMaterialsIndexRoute = ApiCourseMaterialsIndexRouteImport.update({
  id: '/api/course-materials/',
  path: '/api/course-materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdCoursesRoute = ApiStudentsIdCoursesRouteImport.update({
  id: '/api/students/$id/courses',
  path: '/api/students/$id/courses',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/results/': typeof ApiResultsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/course-materials': typeof ApiCourseMaterialsIndexRoute
  '/api/courses': typeof ApiCoursesIndexRoute
  '/api/lab-projects': typeof ApiLabProjectsIndexRoute
  '/api/notices': typeof ApiNoticesIndexRoute
  '/api/payments': typeof ApiPaymentsIndexRoute
  '/api/results': typeof ApiResultsIndexRoute
  '/api/routine': typeof ApiRoutineIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/api/health': typeof ApiHealthRoute
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/results/': typeof ApiResultsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/health'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/payments/'
    | '/api/results/'
    | '/api/routine/'
    | '/api/students/'
    | '/api/students/$id/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/dashboard'
    | '/api/health'
    | '/api/course-materials'
    | '/api/courses'
    | '/api/lab-projects'
    | '/api/notices'
    | '/api/payments'
    | '/api/results'
    | '/api/routine'
    | '/api/students'
    | '/api/students/$id/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/dashboard'
    | '/api/health'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/payments/'
    | '/api/results/'
    | '/api/routine/'
    | '/api/students/'
    | '/api/students/$id/courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiCourseMaterialsIndexRoute: typeof ApiCourseMaterialsIndexRoute
  ApiCoursesIndexRoute: typeof ApiCoursesIndexRoute
  ApiLabProjectsIndexRoute: typeof ApiLabProjectsIndexRoute
  ApiNoticesIndexRoute: typeof ApiNoticesIndexRoute
  ApiPaymentsIndexRoute: typeof ApiPaymentsIndexRoute
  ApiResultsIndexRoute: typeof ApiResultsIndexRoute
  ApiRoutineIndexRoute: typeof ApiRoutineIndexRoute
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
  ApiStudentsIdCoursesRoute: typeof ApiStudentsIdCoursesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/routine/': {
      id: '/api/routine/'
      path: '/api/routine'
      fullPath: '/api/routine/'
      preLoaderRoute: typeof ApiRoutineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/results/': {
      id: '/api/results/'
      path: '/api/results'
      fullPath: '/api/results/'
      preLoaderRoute: typeof ApiResultsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/': {
      id: '/api/payments/'
      path: '/api/payments'
      fullPath: '/api/payments/'
      preLoaderRoute: typeof ApiPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notices/': {
      id: '/api/notices/'
      path: '/api/notices'
      fullPath: '/api/notices/'
      preLoaderRoute: typeof ApiNoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab-projects/': {
      id: '/api/lab-projects/'
      path: '/api/lab-projects'
      fullPath: '/api/lab-projects/'
      preLoaderRoute: typeof ApiLabProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses/': {
      id: '/api/courses/'
      path: '/api/courses'
      fullPath: '/api/courses/'
      preLoaderRoute: typeof ApiCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-materials/': {
      id: '/api/course-materials/'
      path: '/api/course-materials'
      fullPath: '/api/course-materials/'
      preLoaderRoute: typeof ApiCourseMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/courses': {
      id: '/api/students/$id/courses'
      path: '/api/students/$id/courses'
      fullPath: '/api/students/$id/courses'
      preLoaderRoute: typeof ApiStudentsIdCoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiCourseMaterialsIndexRoute: ApiCourseMaterialsIndexRoute,
  ApiCoursesIndexRoute: ApiCoursesIndexRoute,
  ApiLabProjectsIndexRoute: ApiLabProjectsIndexRoute,
  ApiNoticesIndexRoute: ApiNoticesIndexRoute,
  ApiPaymentsIndexRoute: ApiPaymentsIndexRoute,
  ApiResultsIndexRoute: ApiResultsIndexRoute,
  ApiRoutineIndexRoute: ApiRoutineIndexRoute,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
  ApiStudentsIdCoursesRoute: ApiStudentsIdCoursesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
