/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as AuthenticatedOverviewRouteImport } from './routes/_authenticated/overview'
import { Route as ApiStudentsIndexRouteImport } from './routes/api/students/index'
import { Route as ApiRoutineIndexRouteImport } from './routes/api/routine/index'
import { Route as ApiRegistrationsIndexRouteImport } from './routes/api/registrations/index'
import { Route as ApiPaymentsIndexRouteImport } from './routes/api/payments/index'
import { Route as ApiNotificationsIndexRouteImport } from './routes/api/notifications/index'
import { Route as ApiNoticesIndexRouteImport } from './routes/api/notices/index'
import { Route as ApiLabProjectsIndexRouteImport } from './routes/api/lab-projects/index'
import { Route as ApiGradesIndexRouteImport } from './routes/api/grades/index'
import { Route as ApiCoursesIndexRouteImport } from './routes/api/courses/index'
import { Route as ApiCourseMaterialsIndexRouteImport } from './routes/api/course-materials/index'
import { Route as ApiStudentsIdRouteImport } from './routes/api/students/$id'
import { Route as ApiRegistrationsIdRouteImport } from './routes/api/registrations/$id'
import { Route as ApiNoticesIdRouteImport } from './routes/api/notices/$id'
import { Route as ApiStudentsIdCoursesRouteImport } from './routes/api/students/$id.courses'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiGradesPublishOfferingIdRouteImport } from './routes/api/grades/publish.$offeringId'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedOverviewRoute = AuthenticatedOverviewRouteImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const ApiStudentsIndexRoute = ApiStudentsIndexRouteImport.update({
  id: '/api/students/',
  path: '/api/students/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRoutineIndexRoute = ApiRoutineIndexRouteImport.update({
  id: '/api/routine/',
  path: '/api/routine/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsIndexRoute = ApiRegistrationsIndexRouteImport.update({
  id: '/api/registrations/',
  path: '/api/registrations/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsIndexRoute = ApiPaymentsIndexRouteImport.update({
  id: '/api/payments/',
  path: '/api/payments/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNotificationsIndexRoute = ApiNotificationsIndexRouteImport.update({
  id: '/api/notifications/',
  path: '/api/notifications/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoticesIndexRoute = ApiNoticesIndexRouteImport.update({
  id: '/api/notices/',
  path: '/api/notices/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiLabProjectsIndexRoute = ApiLabProjectsIndexRouteImport.update({
  id: '/api/lab-projects/',
  path: '/api/lab-projects/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGradesIndexRoute = ApiGradesIndexRouteImport.update({
  id: '/api/grades/',
  path: '/api/grades/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCoursesIndexRoute = ApiCoursesIndexRouteImport.update({
  id: '/api/courses/',
  path: '/api/courses/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCourseMaterialsIndexRoute = ApiCourseMaterialsIndexRouteImport.update({
  id: '/api/course-materials/',
  path: '/api/course-materials/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdRoute = ApiStudentsIdRouteImport.update({
  id: '/api/students/$id',
  path: '/api/students/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiRegistrationsIdRoute = ApiRegistrationsIdRouteImport.update({
  id: '/api/registrations/$id',
  path: '/api/registrations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNoticesIdRoute = ApiNoticesIdRouteImport.update({
  id: '/api/notices/$id',
  path: '/api/notices/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStudentsIdCoursesRoute = ApiStudentsIdCoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => ApiStudentsIdRoute,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiGradesPublishOfferingIdRoute =
  ApiGradesPublishOfferingIdRouteImport.update({
    id: '/api/grades/publish/$offeringId',
    path: '/api/grades/publish/$offeringId',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/grades/': typeof ApiGradesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/overview': typeof AuthenticatedOverviewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/course-materials': typeof ApiCourseMaterialsIndexRoute
  '/api/courses': typeof ApiCoursesIndexRoute
  '/api/grades': typeof ApiGradesIndexRoute
  '/api/lab-projects': typeof ApiLabProjectsIndexRoute
  '/api/notices': typeof ApiNoticesIndexRoute
  '/api/notifications': typeof ApiNotificationsIndexRoute
  '/api/payments': typeof ApiPaymentsIndexRoute
  '/api/registrations': typeof ApiRegistrationsIndexRoute
  '/api/routine': typeof ApiRoutineIndexRoute
  '/api/students': typeof ApiStudentsIndexRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_authenticated/overview': typeof AuthenticatedOverviewRoute
  '/api/health': typeof ApiHealthRoute
  '/api/notices/$id': typeof ApiNoticesIdRoute
  '/api/registrations/$id': typeof ApiRegistrationsIdRoute
  '/api/students/$id': typeof ApiStudentsIdRouteWithChildren
  '/api/course-materials/': typeof ApiCourseMaterialsIndexRoute
  '/api/courses/': typeof ApiCoursesIndexRoute
  '/api/grades/': typeof ApiGradesIndexRoute
  '/api/lab-projects/': typeof ApiLabProjectsIndexRoute
  '/api/notices/': typeof ApiNoticesIndexRoute
  '/api/notifications/': typeof ApiNotificationsIndexRoute
  '/api/payments/': typeof ApiPaymentsIndexRoute
  '/api/registrations/': typeof ApiRegistrationsIndexRoute
  '/api/routine/': typeof ApiRoutineIndexRoute
  '/api/students/': typeof ApiStudentsIndexRoute
  '/api/grades/publish/$offeringId': typeof ApiGradesPublishOfferingIdRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/students/$id/courses': typeof ApiStudentsIdCoursesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/overview'
    | '/api/health'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/grades/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/registrations/'
    | '/api/routine/'
    | '/api/students/'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/reset-password'
    | '/overview'
    | '/api/health'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/api/course-materials'
    | '/api/courses'
    | '/api/grades'
    | '/api/lab-projects'
    | '/api/notices'
    | '/api/notifications'
    | '/api/payments'
    | '/api/registrations'
    | '/api/routine'
    | '/api/students'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/reset-password'
    | '/_authenticated/overview'
    | '/api/health'
    | '/api/notices/$id'
    | '/api/registrations/$id'
    | '/api/students/$id'
    | '/api/course-materials/'
    | '/api/courses/'
    | '/api/grades/'
    | '/api/lab-projects/'
    | '/api/notices/'
    | '/api/notifications/'
    | '/api/payments/'
    | '/api/registrations/'
    | '/api/routine/'
    | '/api/students/'
    | '/api/grades/publish/$offeringId'
    | '/api/public/payments/webhook'
    | '/api/students/$id/courses'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ApiHealthRoute: typeof ApiHealthRoute
  ApiNoticesIdRoute: typeof ApiNoticesIdRoute
  ApiRegistrationsIdRoute: typeof ApiRegistrationsIdRoute
  ApiStudentsIdRoute: typeof ApiStudentsIdRouteWithChildren
  ApiCourseMaterialsIndexRoute: typeof ApiCourseMaterialsIndexRoute
  ApiCoursesIndexRoute: typeof ApiCoursesIndexRoute
  ApiGradesIndexRoute: typeof ApiGradesIndexRoute
  ApiLabProjectsIndexRoute: typeof ApiLabProjectsIndexRoute
  ApiNoticesIndexRoute: typeof ApiNoticesIndexRoute
  ApiNotificationsIndexRoute: typeof ApiNotificationsIndexRoute
  ApiPaymentsIndexRoute: typeof ApiPaymentsIndexRoute
  ApiRegistrationsIndexRoute: typeof ApiRegistrationsIndexRoute
  ApiRoutineIndexRoute: typeof ApiRoutineIndexRoute
  ApiStudentsIndexRoute: typeof ApiStudentsIndexRoute
  ApiGradesPublishOfferingIdRoute: typeof ApiGradesPublishOfferingIdRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/overview': {
      id: '/_authenticated/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof AuthenticatedOverviewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/api/students/': {
      id: '/api/students/'
      path: '/api/students'
      fullPath: '/api/students/'
      preLoaderRoute: typeof ApiStudentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/routine/': {
      id: '/api/routine/'
      path: '/api/routine'
      fullPath: '/api/routine/'
      preLoaderRoute: typeof ApiRoutineIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/': {
      id: '/api/registrations/'
      path: '/api/registrations'
      fullPath: '/api/registrations/'
      preLoaderRoute: typeof ApiRegistrationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/': {
      id: '/api/payments/'
      path: '/api/payments'
      fullPath: '/api/payments/'
      preLoaderRoute: typeof ApiPaymentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notifications/': {
      id: '/api/notifications/'
      path: '/api/notifications'
      fullPath: '/api/notifications/'
      preLoaderRoute: typeof ApiNotificationsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notices/': {
      id: '/api/notices/'
      path: '/api/notices'
      fullPath: '/api/notices/'
      preLoaderRoute: typeof ApiNoticesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/lab-projects/': {
      id: '/api/lab-projects/'
      path: '/api/lab-projects'
      fullPath: '/api/lab-projects/'
      preLoaderRoute: typeof ApiLabProjectsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grades/': {
      id: '/api/grades/'
      path: '/api/grades'
      fullPath: '/api/grades/'
      preLoaderRoute: typeof ApiGradesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/courses/': {
      id: '/api/courses/'
      path: '/api/courses'
      fullPath: '/api/courses/'
      preLoaderRoute: typeof ApiCoursesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/course-materials/': {
      id: '/api/course-materials/'
      path: '/api/course-materials'
      fullPath: '/api/course-materials/'
      preLoaderRoute: typeof ApiCourseMaterialsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id': {
      id: '/api/students/$id'
      path: '/api/students/$id'
      fullPath: '/api/students/$id'
      preLoaderRoute: typeof ApiStudentsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/registrations/$id': {
      id: '/api/registrations/$id'
      path: '/api/registrations/$id'
      fullPath: '/api/registrations/$id'
      preLoaderRoute: typeof ApiRegistrationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/notices/$id': {
      id: '/api/notices/$id'
      path: '/api/notices/$id'
      fullPath: '/api/notices/$id'
      preLoaderRoute: typeof ApiNoticesIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/students/$id/courses': {
      id: '/api/students/$id/courses'
      path: '/courses'
      fullPath: '/api/students/$id/courses'
      preLoaderRoute: typeof ApiStudentsIdCoursesRouteImport
      parentRoute: typeof ApiStudentsIdRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/grades/publish/$offeringId': {
      id: '/api/grades/publish/$offeringId'
      path: '/api/grades/publish/$offeringId'
      fullPath: '/api/grades/publish/$offeringId'
      preLoaderRoute: typeof ApiGradesPublishOfferingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedOverviewRoute: typeof AuthenticatedOverviewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedOverviewRoute: AuthenticatedOverviewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface ApiStudentsIdRouteChildren {
  ApiStudentsIdCoursesRoute: typeof ApiStudentsIdCoursesRoute
}

const ApiStudentsIdRouteChildren: ApiStudentsIdRouteChildren = {
  ApiStudentsIdCoursesRoute: ApiStudentsIdCoursesRoute,
}

const ApiStudentsIdRouteWithChildren = ApiStudentsIdRoute._addFileChildren(
  ApiStudentsIdRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ApiHealthRoute: ApiHealthRoute,
  ApiNoticesIdRoute: ApiNoticesIdRoute,
  ApiRegistrationsIdRoute: ApiRegistrationsIdRoute,
  ApiStudentsIdRoute: ApiStudentsIdRouteWithChildren,
  ApiCourseMaterialsIndexRoute: ApiCourseMaterialsIndexRoute,
  ApiCoursesIndexRoute: ApiCoursesIndexRoute,
  ApiGradesIndexRoute: ApiGradesIndexRoute,
  ApiLabProjectsIndexRoute: ApiLabProjectsIndexRoute,
  ApiNoticesIndexRoute: ApiNoticesIndexRoute,
  ApiNotificationsIndexRoute: ApiNotificationsIndexRoute,
  ApiPaymentsIndexRoute: ApiPaymentsIndexRoute,
  ApiRegistrationsIndexRoute: ApiRegistrationsIndexRoute,
  ApiRoutineIndexRoute: ApiRoutineIndexRoute,
  ApiStudentsIndexRoute: ApiStudentsIndexRoute,
  ApiGradesPublishOfferingIdRoute: ApiGradesPublishOfferingIdRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
